insert into NewFileSize
select  new_column_length
from 
(
select max(len([eventid])) as new_column_length from GT UNION ALL
select max(len([iyear])) from GT UNION ALL
select max(len([imonth])) from GT UNION ALL
select max(len([iday])) from GT UNION ALL
select max(len([approxdate])) from GT UNION ALL
select max(len([extended])) from GT UNION ALL
select max(len([resolution])) from GT UNION ALL
select max(len([country])) from GT UNION ALL
select max(len([country_txt])) from GT UNION ALL
select max(len([region])) from GT UNION ALL
select max(len([region_txt])) from GT UNION ALL
select max(len([provstate])) from GT UNION ALL
select max(len([city])) from GT UNION ALL
select max(len([latitude])) from GT UNION ALL
select max(len([longitude])) from GT UNION ALL
select max(len([specificity])) from GT UNION ALL
select max(len([vicinity])) from GT UNION ALL
select max(len([location])) from GT UNION ALL
select max(len([summary])) from GT UNION ALL
select max(len([crit1])) from GT UNION ALL
select max(len([crit2])) from GT UNION ALL
select max(len([crit3])) from GT UNION ALL
select max(len([doubtterr])) from GT UNION ALL
select max(len([alternative])) from GT UNION ALL
select max(len([alternative_txt])) from GT UNION ALL
select max(len([multiple])) from GT UNION ALL
select max(len([success])) from GT UNION ALL
select max(len([suicide])) from GT UNION ALL
select max(len([attacktype1])) from GT UNION ALL
select max(len([attacktype1_txt])) from GT UNION ALL
select max(len([attacktype2])) from GT UNION ALL
select max(len([attacktype2_txt])) from GT UNION ALL
select max(len([attacktype3])) from GT UNION ALL
select max(len([attacktype3_txt])) from GT UNION ALL
select max(len([targtype1])) from GT UNION ALL
select max(len([targtype1_txt])) from GT UNION ALL
select max(len([targsubtype1])) from GT UNION ALL
select max(len([targsubtype1_txt])) from GT UNION ALL
select max(len([corp1])) from GT UNION ALL
select max(len([target1])) from GT UNION ALL
select max(len([natlty1])) from GT UNION ALL
select max(len([natlty1_txt])) from GT UNION ALL
select max(len([targtype2])) from GT UNION ALL
select max(len([targtype2_txt])) from GT UNION ALL
select max(len([targsubtype2])) from GT UNION ALL
select max(len([targsubtype2_txt])) from GT UNION ALL
select max(len([corp2])) from GT UNION ALL
select max(len([target2])) from GT UNION ALL
select max(len([natlty2])) from GT UNION ALL
select max(len([natlty2_txt])) from GT UNION ALL
select max(len([targtype3])) from GT UNION ALL
select max(len([targtype3_txt])) from GT UNION ALL
select max(len([targsubtype3])) from GT UNION ALL
select max(len([targsubtype3_txt])) from GT UNION ALL
select max(len([corp3])) from GT UNION ALL
select max(len([target3])) from GT UNION ALL
select max(len([natlty3])) from GT UNION ALL
select max(len([natlty3_txt])) from GT UNION ALL
select max(len([gname])) from GT UNION ALL
select max(len([gsubname])) from GT UNION ALL
select max(len([gname2])) from GT UNION ALL
select max(len([gsubname2])) from GT UNION ALL
select max(len([gname3])) from GT UNION ALL
select max(len([ingroup])) from GT UNION ALL
select max(len([ingroup2])) from GT UNION ALL
select max(len([ingroup3])) from GT UNION ALL
select max(len([gsubname3])) from GT UNION ALL
select max(len([motive])) from GT UNION ALL
select max(len([guncertain1])) from GT UNION ALL
select max(len([guncertain2])) from GT UNION ALL
select max(len([guncertain3])) from GT UNION ALL
select max(len([nperps])) from GT UNION ALL
select max(len([nperpcap])) from GT UNION ALL
select max(len([claimed])) from GT UNION ALL
select max(len([claimmode])) from GT UNION ALL
select max(len([claimmode_txt])) from GT UNION ALL
select max(len([claim2])) from GT UNION ALL
select max(len([claimmode2])) from GT UNION ALL
select max(len([claimmode2_txt])) from GT UNION ALL
select max(len([claim3])) from GT UNION ALL
select max(len([claimmode3])) from GT UNION ALL
select max(len([claimmode3_txt])) from GT UNION ALL
select max(len([compclaim])) from GT UNION ALL
select max(len([weaptype1])) from GT UNION ALL
select max(len([weaptype1_txt])) from GT UNION ALL
select max(len([weapsubtype1])) from GT UNION ALL
select max(len([weapsubtype1_txt])) from GT UNION ALL
select max(len([weaptype2])) from GT UNION ALL
select max(len([weaptype2_txt])) from GT UNION ALL
select max(len([weapsubtype2])) from GT UNION ALL
select max(len([weapsubtype2_txt])) from GT UNION ALL
select max(len([weaptype3])) from GT UNION ALL
select max(len([weaptype3_txt])) from GT UNION ALL
select max(len([weapsubtype3])) from GT UNION ALL
select max(len([weapsubtype3_txt])) from GT UNION ALL
select max(len([weaptype4])) from GT UNION ALL
select max(len([weaptype4_txt])) from GT UNION ALL
select max(len([weapsubtype4])) from GT UNION ALL
select max(len([weapsubtype4_txt])) from GT UNION ALL
select max(len([weapdetail])) from GT UNION ALL
select max(len([nkill])) from GT UNION ALL
select max(len([nkillus])) from GT UNION ALL
select max(len([nkillter])) from GT UNION ALL
select max(len([nwound])) from GT UNION ALL
select max(len([nwoundus])) from GT UNION ALL
select max(len([nwoundte])) from GT UNION ALL
select max(len([property])) from GT UNION ALL
select max(len([propextent])) from GT UNION ALL
select max(len([propextent_txt])) from GT UNION ALL
select max(len([propvalue])) from GT UNION ALL
select max(len([propcomment])) from GT UNION ALL
select max(len([ishostkid])) from GT UNION ALL
select max(len([nhostkid])) from GT UNION ALL
select max(len([nhostkidus])) from GT UNION ALL
select max(len([nhours])) from GT UNION ALL
select max(len([ndays])) from GT UNION ALL
select max(len([divert])) from GT UNION ALL
select max(len([kidhijcountry])) from GT UNION ALL
select max(len([ransom])) from GT UNION ALL
select max(len([ransomamt])) from GT UNION ALL
select max(len([ransomamtus])) from GT UNION ALL
select max(len([ransompaid])) from GT UNION ALL
select max(len([ransompaidus])) from GT UNION ALL
select max(len([ransomnote])) from GT UNION ALL
select max(len([hostkidoutcome])) from GT UNION ALL
select max(len([hostkidoutcome_txt])) from GT UNION ALL
select max(len([nreleased])) from GT UNION ALL
select max(len([addnotes])) from GT UNION ALL
select max(len([scite1])) from GT UNION ALL
select max(len([scite2])) from GT UNION ALL
select max(len([scite3])) from GT UNION ALL
select max(len([dbsource])) from GT UNION ALL
select max(len([INT_LOG])) from GT UNION ALL
select max(len([INT_IDEO])) from GT UNION ALL
select max(len([INT_MISC])) from GT UNION ALL
select max(len([INT_ANY])) from GT UNION ALL
select max(len([related])) from GT 
) as T1