bcp [Global_Terrorism].[dbo].[addnotes_TBL] out addnotes_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[alternative_TBL] out alternative_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[alternative_txt_TBL] out alternative_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[approxdate_TBL] out approxdate_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[attacktype1_TBL] out attacktype1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[attacktype1_txt_TBL] out attacktype1_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[attacktype2_TBL] out attacktype2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[attacktype2_txt_TBL] out attacktype2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[attacktype3_TBL] out attacktype3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[attacktype3_txt_TBL] out attacktype3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[city_TBL] out city_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claim2_TBL] out claim2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claim3_TBL] out claim3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimed_TBL] out claimed_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimmode_TBL] out claimmode_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimmode_txt_TBL] out claimmode_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimmode2_TBL] out claimmode2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimmode2_txt_TBL] out claimmode2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimmode3_TBL] out claimmode3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[claimmode3_txt_TBL] out claimmode3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[compclaim_TBL] out compclaim_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[corp1_TBL] out corp1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[corp2_TBL] out corp2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[corp3_TBL] out corp3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[country_TBL] out country_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[country_txt_TBL] out country_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[crit1_TBL] out crit1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[crit2_TBL] out crit2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[crit3_TBL] out crit3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[dbsource_TBL] out dbsource_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[divert_TBL] out divert_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[doubtterr_TBL] out doubtterr_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[eventid_TBL] out eventid_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[extended_TBL] out extended_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[gname_TBL] out gname_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[gname2_TBL] out gname2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[gname3_TBL] out gname3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[gsubname_TBL] out gsubname_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[gsubname2_TBL] out gsubname2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[gsubname3_TBL] out gsubname3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[guncertain1_TBL] out guncertain1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[guncertain2_TBL] out guncertain2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[guncertain3_TBL] out guncertain3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[hostkidoutcome_TBL] out hostkidoutcome_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[hostkidoutcome_txt_TBL] out hostkidoutcome_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[iday_TBL] out iday_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[imonth_TBL] out imonth_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ingroup_TBL] out ingroup_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ingroup2_TBL] out ingroup2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ingroup3_TBL] out ingroup3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[INT_ANY_TBL] out INT_ANY_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[INT_IDEO_TBL] out INT_IDEO_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[INT_LOG_TBL] out INT_LOG_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[INT_MISC_TBL] out INT_MISC_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ishostkid_TBL] out ishostkid_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[iyear_TBL] out iyear_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[kidhijcountry_TBL] out kidhijcountry_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[latitude_TBL] out latitude_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[location_TBL] out location_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[longitude_TBL] out longitude_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[motive_TBL] out motive_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[multiple_TBL] out multiple_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[natlty1_TBL] out natlty1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[natlty1_txt_TBL] out natlty1_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[natlty2_TBL] out natlty2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[natlty2_txt_TBL] out natlty2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[natlty3_TBL] out natlty3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[natlty3_txt_TBL] out natlty3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ndays_TBL] out ndays_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nhostkid_TBL] out nhostkid_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nhostkidus_TBL] out nhostkidus_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nhours_TBL] out nhours_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nkill_TBL] out nkill_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nkillter_TBL] out nkillter_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nkillus_TBL] out nkillus_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nperpcap_TBL] out nperpcap_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nperps_TBL] out nperps_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nreleased_TBL] out nreleased_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nwound_TBL] out nwound_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nwoundte_TBL] out nwoundte_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[nwoundus_TBL] out nwoundus_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[propcomment_TBL] out propcomment_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[property_TBL] out property_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[propextent_TBL] out propextent_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[propextent_txt_TBL] out propextent_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[propvalue_TBL] out propvalue_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[provstate_TBL] out provstate_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ransom_TBL] out ransom_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ransomamt_TBL] out ransomamt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ransomamtus_TBL] out ransomamtus_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ransomnote_TBL] out ransomnote_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ransompaid_TBL] out ransompaid_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[ransompaidus_TBL] out ransompaidus_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[region_TBL] out region_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[region_txt_TBL] out region_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[related_TBL] out related_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[resolution_TBL] out resolution_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[scite1_TBL] out scite1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[scite2_TBL] out scite2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[scite3_TBL] out scite3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[specificity_TBL] out specificity_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[success_TBL] out success_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[suicide_TBL] out suicide_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[summary_TBL] out summary_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[target1_TBL] out target1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[target2_TBL] out target2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[target3_TBL] out target3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targsubtype1_TBL] out targsubtype1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targsubtype1_txt_TBL] out targsubtype1_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targsubtype2_TBL] out targsubtype2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targsubtype2_txt_TBL] out targsubtype2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targsubtype3_TBL] out targsubtype3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targsubtype3_txt_TBL] out targsubtype3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targtype1_TBL] out targtype1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targtype1_txt_TBL] out targtype1_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targtype2_TBL] out targtype2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targtype2_txt_TBL] out targtype2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targtype3_TBL] out targtype3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[targtype3_txt_TBL] out targtype3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[vicinity_TBL] out vicinity_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapdetail_TBL] out weapdetail_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype1_TBL] out weapsubtype1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype1_txt_TBL] out weapsubtype1_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype2_TBL] out weapsubtype2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype2_txt_TBL] out weapsubtype2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype3_TBL] out weapsubtype3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype3_txt_TBL] out weapsubtype3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype4_TBL] out weapsubtype4_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weapsubtype4_txt_TBL] out weapsubtype4_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype1_TBL] out weaptype1_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype1_txt_TBL] out weaptype1_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype2_TBL] out weaptype2_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype2_txt_TBL] out weaptype2_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype3_TBL] out weaptype3_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype3_txt_TBL] out weaptype3_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype4_TBL] out weaptype4_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T
bcp [Global_Terrorism].[dbo].[weaptype4_txt_TBL] out weaptype4_txt_TBL.csv -w -t"," -E -S MAXHERRERAD577 -T