select *
into DISTRIBUTION_TABLE
FROM
(
Select 'addnotes_TBL' as TABLENAME, column1 as DATAVALUES, percent_of_total from addnotes_TBL union all 
Select 'alternative_TBL', * from alternative_TBL union all 
Select 'alternative_txt_TBL', * from alternative_txt_TBL union all 
Select 'approxdate_TBL', * from approxdate_TBL union all 
Select 'attacktype1_TBL', * from attacktype1_TBL union all 
Select 'attacktype1_txt_TBL', * from attacktype1_txt_TBL union all 
Select 'attacktype2_TBL', * from attacktype2_TBL union all 
Select 'attacktype2_txt_TBL', * from attacktype2_txt_TBL union all 
Select 'attacktype3_TBL', * from attacktype3_TBL union all 
Select 'attacktype3_txt_TBL', * from attacktype3_txt_TBL union all 
Select 'city_TBL', * from city_TBL union all 
Select 'claim2_TBL', * from claim2_TBL union all 
Select 'claim3_TBL', * from claim3_TBL union all 
Select 'claimed_TBL', * from claimed_TBL union all 
Select 'claimmode_TBL', * from claimmode_TBL union all 
Select 'claimmode_txt_TBL', * from claimmode_txt_TBL union all 
Select 'claimmode2_TBL', * from claimmode2_TBL union all 
Select 'claimmode2_txt_TBL', * from claimmode2_txt_TBL union all 
Select 'claimmode3_TBL', * from claimmode3_TBL union all 
Select 'claimmode3_txt_TBL', * from claimmode3_txt_TBL union all 
Select 'compclaim_TBL', * from compclaim_TBL union all 
Select 'corp1_TBL', * from corp1_TBL union all 
Select 'corp2_TBL', * from corp2_TBL union all 
Select 'corp3_TBL', * from corp3_TBL union all 
Select 'country_TBL', * from country_TBL union all 
Select 'country_txt_TBL', * from country_txt_TBL union all 
Select 'crit1_TBL', * from crit1_TBL union all 
Select 'crit2_TBL', * from crit2_TBL union all 
Select 'crit3_TBL', * from crit3_TBL union all 
Select 'dbsource_TBL', * from dbsource_TBL union all 
Select 'divert_TBL', * from divert_TBL union all 
Select 'doubtterr_TBL', * from doubtterr_TBL union all 
Select 'eventid_TBL', * from eventid_TBL union all 
Select 'extended_TBL', * from extended_TBL union all 
Select 'gname_TBL', * from gname_TBL union all 
Select 'gname2_TBL', * from gname2_TBL union all 
Select 'gname3_TBL', * from gname3_TBL union all 
Select 'gsubname_TBL', * from gsubname_TBL union all 
Select 'gsubname2_TBL', * from gsubname2_TBL union all 
Select 'gsubname3_TBL', * from gsubname3_TBL union all 
Select 'guncertain1_TBL', * from guncertain1_TBL union all 
Select 'guncertain2_TBL', * from guncertain2_TBL union all 
Select 'guncertain3_TBL', * from guncertain3_TBL union all 
Select 'hostkidoutcome_TBL', * from hostkidoutcome_TBL union all 
Select 'hostkidoutcome_txt_TBL', * from hostkidoutcome_txt_TBL union all 
Select 'iday_TBL', * from iday_TBL union all 
Select 'imonth_TBL', * from imonth_TBL union all 
Select 'ingroup_TBL', * from ingroup_TBL union all 
Select 'ingroup2_TBL', * from ingroup2_TBL union all 
Select 'ingroup3_TBL', * from ingroup3_TBL union all 
Select 'INT_ANY_TBL', * from INT_ANY_TBL union all 
Select 'INT_IDEO_TBL', * from INT_IDEO_TBL union all 
Select 'INT_LOG_TBL', * from INT_LOG_TBL union all 
Select 'INT_MISC_TBL', * from INT_MISC_TBL union all 
Select 'ishostkid_TBL', * from ishostkid_TBL union all 
Select 'iyear_TBL', * from iyear_TBL union all 
Select 'kidhijcountry_TBL', * from kidhijcountry_TBL union all 
Select 'latitude_TBL', * from latitude_TBL union all 
Select 'location_TBL', * from location_TBL union all 
Select 'longitude_TBL', * from longitude_TBL union all 
Select 'motive_TBL', * from motive_TBL union all 
Select 'multiple_TBL', * from multiple_TBL union all 
Select 'natlty1_TBL', * from natlty1_TBL union all 
Select 'natlty1_txt_TBL', * from natlty1_txt_TBL union all 
Select 'natlty2_TBL', * from natlty2_TBL union all 
Select 'natlty2_txt_TBL', * from natlty2_txt_TBL union all 
Select 'natlty3_TBL', * from natlty3_TBL union all 
Select 'natlty3_txt_TBL', * from natlty3_txt_TBL union all 
Select 'ndays_TBL', * from ndays_TBL union all 
Select 'nhostkid_TBL', * from nhostkid_TBL union all 
Select 'nhostkidus_TBL', * from nhostkidus_TBL union all 
Select 'nhours_TBL', * from nhours_TBL union all 
Select 'nkill_TBL', * from nkill_TBL union all 
Select 'nkillter_TBL', * from nkillter_TBL union all 
Select 'nkillus_TBL', * from nkillus_TBL union all 
Select 'nperpcap_TBL', * from nperpcap_TBL union all 
Select 'nperps_TBL', * from nperps_TBL union all 
Select 'nreleased_TBL', * from nreleased_TBL union all 
Select 'nwound_TBL', * from nwound_TBL union all 
Select 'nwoundte_TBL', * from nwoundte_TBL union all 
Select 'nwoundus_TBL', * from nwoundus_TBL union all 
Select 'propcomment_TBL', * from propcomment_TBL union all 
Select 'property_TBL', * from property_TBL union all 
Select 'propextent_TBL', * from propextent_TBL union all 
Select 'propextent_txt_TBL', * from propextent_txt_TBL union all 
Select 'propvalue_TBL', * from propvalue_TBL union all 
Select 'provstate_TBL', * from provstate_TBL union all 
Select 'ransom_TBL', * from ransom_TBL union all 
Select 'ransomamt_TBL', * from ransomamt_TBL union all 
Select 'ransomamtus_TBL', * from ransomamtus_TBL union all 
Select 'ransomnote_TBL', * from ransomnote_TBL union all 
Select 'ransompaid_TBL', * from ransompaid_TBL union all 
Select 'ransompaidus_TBL', * from ransompaidus_TBL union all 
Select 'region_TBL', * from region_TBL union all 
Select 'region_txt_TBL', * from region_txt_TBL union all 
Select 'related_TBL', * from related_TBL union all 
Select 'resolution_TBL', * from resolution_TBL union all 
Select 'scite1_TBL', * from scite1_TBL union all 
Select 'scite2_TBL', * from scite2_TBL union all 
Select 'scite3_TBL', * from scite3_TBL union all 
Select 'specificity_TBL', * from specificity_TBL union all 
Select 'success_TBL', * from success_TBL union all 
Select 'suicide_TBL', * from suicide_TBL union all 
Select 'summary_TBL', * from summary_TBL union all 
Select 'target1_TBL', * from target1_TBL union all 
Select 'target2_TBL', * from target2_TBL union all 
Select 'target3_TBL', * from target3_TBL union all 
Select 'targsubtype1_TBL', * from targsubtype1_TBL union all 
Select 'targsubtype1_txt_TBL', * from targsubtype1_txt_TBL union all 
Select 'targsubtype2_TBL', * from targsubtype2_TBL union all 
Select 'targsubtype2_txt_TBL', * from targsubtype2_txt_TBL union all 
Select 'targsubtype3_TBL', * from targsubtype3_TBL union all 
Select 'targsubtype3_txt_TBL', * from targsubtype3_txt_TBL union all 
Select 'targtype1_TBL', * from targtype1_TBL union all 
Select 'targtype1_txt_TBL', * from targtype1_txt_TBL union all 
Select 'targtype2_TBL', * from targtype2_TBL union all 
Select 'targtype2_txt_TBL', * from targtype2_txt_TBL union all 
Select 'targtype3_TBL', * from targtype3_TBL union all 
Select 'targtype3_txt_TBL', * from targtype3_txt_TBL union all 
Select 'vicinity_TBL', * from vicinity_TBL union all 
Select 'weapdetail_TBL', * from weapdetail_TBL union all 
Select 'weapsubtype1_TBL', * from weapsubtype1_TBL union all 
Select 'weapsubtype1_txt_TBL', * from weapsubtype1_txt_TBL union all 
Select 'weapsubtype2_TBL', * from weapsubtype2_TBL union all 
Select 'weapsubtype2_txt_TBL', * from weapsubtype2_txt_TBL union all 
Select 'weapsubtype3_TBL', * from weapsubtype3_TBL union all 
Select 'weapsubtype3_txt_TBL', * from weapsubtype3_txt_TBL union all 
Select 'weapsubtype4_TBL', * from weapsubtype4_TBL union all 
Select 'weapsubtype4_txt_TBL', * from weapsubtype4_txt_TBL union all 
Select 'weaptype1_TBL', * from weaptype1_TBL union all 
Select 'weaptype1_txt_TBL', * from weaptype1_txt_TBL union all 
Select 'weaptype2_TBL', * from weaptype2_TBL union all 
Select 'weaptype2_txt_TBL', * from weaptype2_txt_TBL union all 
Select 'weaptype3_TBL', * from weaptype3_TBL union all 
Select 'weaptype3_txt_TBL', * from weaptype3_txt_TBL union all 
Select 'weaptype4_TBL', * from weaptype4_TBL union all 
Select 'weaptype4_txt_TBL', * from weaptype4_txt_TBL
) AS T1
order by 1,3 desc